spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
        security: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem