spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: WARN
    org:
      springframework:
        web: WARN
        security: DEBUG

rsa:
  private-key: ${RSA_PRIVATE_KEY:classpath:certs/private.pem}
  public-key: ${RSA_PUBLIC_KEY:classpath:certs/public.pem}