spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

server:
  port: ${PORT}

admin:
  email: ${ADMIN_EMAIL:hexlet@example.com}
  password: ${ADMIN_PASSWORD:qwerty}

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0